### ISSUE TITLE
Registro do domínio

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/openschoolbr.github.io#4]
_From @kvnol on August 3, 2017 14:16_

Galera, quando o @rubenmarcus fez a sugestão do nome para ver se o domínio estava disponível e achei essa domínio que seria ótimo para padronizarmos a marca: **org.br**. O que acham?

![image](https://user-images.githubusercontent.com/3299130/28926090-2a188882-783d-11e7-8f43-8cc2867ddd8a.png)

_Copied from original issue: openschoolbr/forum#4_

**Comment by kvnol** [comment]
_From @muniz95 on August 3, 2017 14:27_

@kvnol show de bola. Só não sei como faríamos com essa questão de comprovar que somos uma ONG de fato, não tenho experiência com isso 😕

**Comment by kvnol** [comment]
_From @khaosdoctor on August 3, 2017 14:54_

Tem que ter um CNPJ que comprove, é uma coisa meio chata... Mas eu acho que o @woliveiras teve esse problema no ABCDev que tem o domínio .org também

**Comment by yuriploc** [comment]
@kvnol algum update sobre?

**Comment by kvnol** [comment]
Então, não sei se o @woliveiras viu essa issue. Porque este domínio é o que faria mais sentido para a org. Mas, pelo o que os amigos citaram, teríamos que abrir um CNPJ como ong.

**Comment by khaosdoctor** [comment]
Sim, isso é um problema. Mas eu vejo muita informação desencontrada, por exemplo:

Achei [este site](http://www.hardware.com.br/comunidade/registro-dominios/120181/) que é um fórum perguntando como funciona esse tipo de domínio, ai temos um comentário:

> .ORG.BR - Exige-se a documentação que comprove a natureza da instituição não governamental sem fins lucrativos e o CNPJ. Nos casos em que a instituição é um consulado ou uma embaixada, a exigência do CNPJ para esse DPN é dispensada;

Porém um pouco mais embaixo temos:

> Domínios .ORG seguem as mesmas regras dos domínios .COM e .NET. Devem ser registrados em alguma entidade internacional habilitada para tal operação. Não são necessários quaisquer documentos adicionais.

Ai fica meio complicado de entender. Procurei um pouco mais e descobri [este guia da localweb](https://wiki.locaweb.com.br/pt-br/Documenta%C3%A7%C3%A3o_necess%C3%A1ria_para_o_registro_de_um_dom%C3%ADnio_.BR) para os domínios no BR e a documentação necessária para cada um, parece que realmente é necessário um CNPJ.

#### Referência extra
- [Godaddy](https://br.godaddy.com/tlds/org-domain)

**Comment by yuriploc** [comment]
A questão é o .br.. Se for só .org minha memória diz que é menos burocrático

On Aug 4, 2017 20:48, "Lucas Santos" <notifications@github.com> wrote:

Sim, isso é um problema. Mas eu vejo muita informação desencontrada, por
exemplo:

Achei este site
<http://www.hardware.com.br/comunidade/registro-dominios/120181/> que é um
fórum perguntando como funciona esse tipo de domínio, ai temos um
comentário:

.ORG.BR - Exige-se a documentação que comprove a natureza da instituição
não governamental sem fins lucrativos e o CNPJ. Nos casos em que a
instituição é um consulado ou uma embaixada, a exigência do CNPJ para esse
DPN é dispensada;

Porém um pouco mais embaixo temos:

Domínios .ORG seguem as mesmas regras dos domínios .COM e .NET. Devem ser
registrados em alguma entidade internacional habilitada para tal operação.
Não são necessários quaisquer documentos adicionais.

Ai fica meio complicado de entender. Procurei um pouco mais e descobri este
guia da localweb
<https://wiki.locaweb.com.br/pt-br/Documenta%C3%A7%C3%A3o_necess%C3%A1ria_para_o_registro_de_um_dom%C3%ADnio_.BR>
para os domínios no BR e a documentação necessária para cada um, parece que
realmente é necessário um CNPJ.
Referência extra

   - Godaddy <https://br.godaddy.com/tlds/org-domain>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openschoolbr/openschoolbr.github.io/issues/4#issuecomment-320376052>,
or mute the thread

**Comment by kvnol** [comment]
A princípio seria interessante, então, registrarmos o .com.br e mais tarde, ao abrir um CNPJ para a Open School (até para um papo futuro sobre [diplomas e certificados](https://github.com/openschoolbr/forum/issues/12)). 

O domínio openschool.com.br e open-school.com.br já está registrado, mas estou entrando em contato com o dono do domínio:

![image](https://user-images.githubusercontent.com/3299130/28995827-c3356dae-79c9-11e7-9aca-97db8da48183.png)

**Comment by andersoonweb** [comment]
@kvnol pq não lançar com o domínio do github pages? Acredito que ficaria bem legal, esse domínio já está mt familiar pra nós e pode despertar a curiosidade de um cara novo que irá adentrar na área.

**Comment by nandomoreirame** [comment]
eu concordo com @andersoonweb, hoje em dia da pra fazer tudo com _statics generators_, se a ideia é ser tudo open deixar o nosso próprio site open usando Jekyll ou similar e ainda usando o próprio _gh-pages domain_ seria uma solução bem legal.

**Comment by andersoonweb** [comment]
Só mais uma coisa: a idéia vai estar no ar beeem mais rápido!

**Comment by khaosdoctor** [comment]
@kvnol e OpenSchool tudo junto?

**Comment by kvnol** [comment]
@khaosdoctor, foi o que eu disse.

> O domínio openschool.com.br e open-school.com.br já está registrado

**Comment by kvnol** [comment]
Eu gosto da ideia, também, de deixar no github.io.

**Comment by khaosdoctor** [comment]
@kvnol Opa! Não tinha lido o tudo junto.

**Comment by khaosdoctor** [comment]
@kvnol Conseguiu algum progresso nessa parte?

**Comment by kvnol** [comment]
@khaosdoctor não recebi nenhuma resposta dos e-mails enviados, estou tentando contato novamente, mas por enquanto vamos deixar no github.io.

**Comment by khaosdoctor** [comment]
Ok, vou fechar essa então

**Comment by gabrieldarezzo** [comment]
Pode ser de maneira progressiva tmb, (mantem no github.io) depois compra o domínio.

Se liga nesse post do Fernando:
https://blog.da2k.com.br/2015/02/05/segredos-do-github-hospedando-seu-site-no-github/
